### ISSUE TITLE
examples/view_idaho_image is broken

### ISSUE THREAD

**Issue by nricklin** [kostasthebarbarian/gbdxtools#13]
here's the output I get:

```
2016-04-01 12:53:57,124 - gbdxtools - INFO - Logger initialized
/Users/nricklin/gbd/gbdxtools/venv/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
  SNIMissingWarning
/Users/nricklin/gbd/gbdxtools/venv/lib/python2.7/site-packages/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
2016-04-01 12:54:02,545 - gbdxtools - DEBUG - Retrieving IDAHO metadata
2016-04-01 12:54:02,545 - gbdxtools - DEBUG - Retrieving strip footprint
Traceback (most recent call last):
  File "view_idaho_image.py", line 10, in <module>
    idaho_images = gbdx.idaho.get_images_by_catid(catid)
  File "/Users/nricklin/gbd/gbdxtools/venv/lib/python2.7/site-packages/gbdxtools/idaho.py", line 62, in get_images_by_catid
    r = self.gbdx_connection.post(url, data=json.dumps(body), headers=headers)
NameError: global name 'json' is not defined
```

**Comment by nricklin** [comment]
thanks for merging!

**Comment by kostasthebarbarian** [comment]
Bitte shon.

We still need to fix the tests and a couple of other bugs. Then we can
merge with master and upgrade the version.
